app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,EmailField,SubmitField,BooleanField
from wtforms.validators import DataRequired,Length,EqualTo,Email
from wtforms.widgets import TextArea
class Signup(FlaskForm):
    username = StringField(label='Enter username', validators=[DataRequired(),Length(min=3,max=200)])
    email = EmailField(label='Enter your email', validators=[DataRequired(),Email()])
    password = PasswordField(label='Enter password', validators=[DataRequired(),Length(min=5,max=150)])
    confirm_password = PasswordField(label='Confirm password', validators=[DataRequired(),EqualTo('password')])
    submit = SubmitField(label='Sign up')

class LogIn(FlaskForm):
    username = StringField(label='Enter username', validators=[DataRequired(),Length(min=3,max=200)])
    password = PasswordField(label='Enter password', validators=[DataRequired(),Length(min=5,max=150)])  
    remember = BooleanField('Remember me')
    submit = SubmitField(label='Log In')

class Blog(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = StringField('Content', validators=[DataRequired()], widget=TextArea())
    author = StringField('Author', validators=[DataRequired()])
    submit = SubmitField(label='submit')    

app/__init__.py
from flask import Flask
from .config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

login_manager = LoginManager()
db = SQLAlchemy()
from .model import User

# Initializing application
def create_app(config_name):
    app = Flask(__name__)

    app.config.from_object(config_options[config_name])

    from .main import main_blueprint
    app.register_blueprint(main_blueprint)

    db.init_app(app)
    login_manager.init_app(app)
    migrate = Migrate(app, db)

    return app
    

app/main/__init__.py
from flask import Blueprint

main_blueprint = Blueprint('main_blueprint', __name__)

from . import views

app/main/views.py
from . import main_blueprint
from flask import render_template, url_for, redirect, flash, request, abort
from .forms import Blog, LogIn, Signup
from ..model import Blogs, User
from flask_login import login_user, logout_user, login_required
from app import db
from ..request import get_quotes

@main_blueprint.route('/home')
@main_blueprint.route('/')
def index():
    return render_template('index.html')

@main_blueprint.route('/blogs', methods=['POST', 'GET'])
def blogs():
    form = Blog()
    if form.validate_on_submit():
        post = Blogs(title=form.title.data, content=form.content.data, author=form.author.data)
        # Clear the form
        form.title.data=''
        form.content.data=''
        form.author.data=''
        # Add post to database
        db.session.add(post)
        db.session.commit()

        flash('Post submitted successfully')

    return render_template('blog.html', form=form) 

@main_blueprint.route('/about')
def about():
    return render_template('about.html')       

@main_blueprint.route('/quotes')
def quotes():
    quotes=get_quotes()
    return render_template('quotes.html', quotes=quotes) 

@main_blueprint.route('/login', methods=['GET', 'POST'] )
def login():
    form=LogIn()
    if form.validate_on_submit():
        user=User.query.filter_by(username = form.username.data).first()
        if user is not None and user.verify_password(form.password.data):
            login_user(user,form.remember.data)
            return redirect(request.args.get('next') or url_for('main_blueprint.blogs'))  

        flash('Invalid username or Password')
        
    return render_template('login.html', form=form)

@main_blueprint.route("/signup", methods=['POST', 'GET'])
def sign_up():
    signup_form = Signup()
    if signup_form.validate_on_submit():
        user = User(email = signup_form.email.data, username = signup_form.username.data,password = signup_form.password.data)
        db.session.add(user)
        db.session.commit()
        flash(f'Successfully signed in for {signup_form.username.data}', category='success')
        return redirect(url_for('main_blueprint.login'))   
    return render_template("signup.html", form=signup_form)      

@main_blueprint.route('/profile/<uname>')
def profile(uname):
    user = User.query.filter_by(username=uname).first()
    if user is None:
        abort(404)
    return render_template('profile.html', user=user) 

@main_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for("main_blueprint.index"))

app/templates/about.html
{% extends 'base.html'%}

{%block content%}

<div class="container d-flex justify-content-center">
<div class="card" style="width: 20rem;">
    <img src="{{url_for('static',filename='images/me.jpeg')}}" class="card-img-top" alt="...">
    <div class="card-body">
        <h1 class="card-title text-uppercase">About Me</h1>
        <p class="card-text text-center">
            I've never been a big admirer of self-promotion. I'm never quite sure what to say. When someone says, "Tell me about yourself," I usually find it cliche. Why not ask the questions you've been thinking about? I'm sure you had an idea of what you wanted to ask when that notion occurred to you. <br> <br> But I'll tell you a little bit about myself. I enjoy reading. It brings me great joy and relieves my tension. I enjoy living a fantasy because life is difficult and we need to find joy in the small things. My safe havens are books. So when I'm mad, angry, sad, or depressed, I read. Basically, I read at any given moment.  
        </p>
    </div>
</div>
</div>


{%endblock%}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta charset="UTF-8">
    <title>{% block title%} Tasha's Blog {%endblock%}</title>
    {% block styles%}
    {{super}}
    <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
    {%endblock%}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous" defer></script>
    {%endblock%}
</head>
</head>
<body>
<!-- Navbar -->
{% include "navbar.html"%}

    <!-- Main Content -->
    {% block content %}
    
    {% endblock %}

</body>
</html>

app/templates/blog.html
{% extends 'base.html'%}

app/templates/index.html
{% extends 'base.html'%}
<title>{% block title%} Tasha's Blog {%endblock%}</title>


{%block content%}
<div class="container justify-content-center d-flex">
    <div class="card" style="width: 30rem;">
        <div class="card-body text-center">
            <h1 class="card-title fs-1 fw-bold">BLOG LOVERS</h1> <br>
            <p class="card-text text-uppercase fs-3">Lets read and talk.</p>
            {%if current_user.is_authenticated%}
            <a href="{{url_for('main_blueprint.profile',uname=current_user.username)}}">
                <button type="button" class="btn" style="color: #6ABEA7;" target="blank">Profile</button>
            </a>
            <a href="/logout">
                <button type="button" class="btn" style="color: #6ABEA7;" target="blank">Logout</button>
            </a>
            {%else%}
            <a href="/login">
                <button type="button" class="btn" style="color: #6ABEA7;" target="blank">Log In</button>
            </a>
            <a href="/signup">
                <button type="button" class="btn" style="color: #6ABEA7;" target="blank">Sign Up</button>
            </a>
            {%endif%}
        </div>
    </div>
</div>
{%endblock%}

app/templates/login.html
{%extends 'base.html'%}
<title>{% block title%} Log In {%endblock%}</title>

{%block content%}
<div class="container w-50">
    <form method="POST" action="">
        {{form.hidden_tag()}}
        <fieldset>
            <legend class="border-bottom mb-4 text-center">Log In</legend>
            <div class="form-group">
                {{form.username.label(class="form-control-label")}}
                {% if form.username.error %}
                {{form.username(class="form-control form-control-lg is-invalid")}}
                {%for error in form.username.errors%}
                {{form.username(class="form-control form-control-lg")}}
                <span>{{error}}</span>
                {%endfor%}
                {%else%}
                {{form.username(class="form-control form-control-lg")}}
                {% endif %}
            </div>
            <div class="form-group">
                {{form.password.label(class="form-control-label")}}
                {% if form.password.error %}
                {{form.password(class="form-control form-control-lg is-invalid")}}
                {%for error in form.password.errors%}
                {{form.password(class="form-control form-control-lg")}}
                <span>{{error}}</span>
                {%endfor%}
                {%else%}
                {{form.password(class="form-control form-control-lg")}}
                {% endif %}
            </div>  
            {{form.remember}} 
            {{form.remember.label(class="form-control-label")}}    
        </fieldset>
        <div class="field group mt-4">            
            {{form.submit(class='btn btn-success')}}
        </div>
    </form>
</div>

{%endblock%}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark" id="myNavbar">
    <div class="container-fluid">
      <a class="navbar-brand text-uppercase fs-1 fw-bold" href="index.html">Tasha's Blog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/home">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/about">About Me</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/quotes">Quotes</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
  

app/templates/profile.html
{%extends 'base.html'%}

{% block contents %}
{% for message in get_flashed_message %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{message}}
</div>
{% endfor %}

<h1>Add to Blog</h1>
<div class="shadow p-3 mb-5 bg-body rounded">
    <form method="POST">
        {{form.hidden_tag()}}

        {{form.title.label(class="form-label")}}
        {{form.title(class="form-control")}}

        {{form.author.label(class="form-label")}}
        {{form.author(class="form-control")}}

        {{form.content.label(class="form-label")}}
        {{form.content(class="form-control")}}



    </form>
</div>

{% endblock %}

app/templates/quotes.html
{%extends 'base.html'%}
<title>{% block title%} Quotes {%endblock%}</title>

{%block content%}

<section>
    <h1 class="text-center mb-5 text-light" > Random Quotes </h1>

    <div class="container mb-5">
        <h3 class="text-center text-capitalize"> {{id}} </h3>
        <div class="row">
            {% for quote in quotes%}
            <div class="col">
                <div class="card h-100">
                    <div class="card-body">
                        <p class="card-text fw-bold"> Author: {{quotes['author']}}</p>
                        <p class="card-text">{{quotes['quote']}}</p>
                        <a href="">
                            <button type="button" class="btn" style="color: #6ABEA7;" target="blank"> Refresh for new quotes</button>
                        </a>
                    </div>
                    <div class="card-footer">
                        <p>  </p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock %}

app/templates/signup.html
{%extends 'base.html'%}
<title>{% block title%} Sign-Up {%endblock%}</title>

{%block content%}
<div class="container w-50">
    <form method="POST" action="">
        {{form.hidden_tag()}}
        <fieldset>
            <legend class="border-bottom mb-4 text-center">Sign-Up</legend>
            <div class="form-group">
                {{form.username.label(class="form-control-label")}}
                {% if form.username.error %}
                {{form.username(class="form-control form-control-lg is-invalid")}}
                {%for error in form.username.errors%}
                {{form.username(class="form-control form-control-lg")}}
                <span>{{error}}</span>
                {%endfor%}
                {%else%}
                {{form.username(class="form-control form-control-lg")}}
                {% endif %}
            </div>
            <div class="form-group">
                {{form.email.label(class="form-control-label")}}
                {% if form.email.error %}
                {{form.email(class="form-control form-control-lg is-invalid")}}
                {%for error in form.email.errors%}
                {{form.email(class="form-control form-control-lg")}}
                <span>{{error}}</span>
                {%endfor%}
                {%else%}
                {{form.email(class="form-control form-control-lg")}}
                {% endif %}
            </div>
            <div class="form-group">
                {{form.password.label(class="form-control-label")}}
                {% if form.password.error %}
                {{form.password(class="form-control form-control-lg is-invalid")}}
                {%for error in form.password.errors%}
                {{form.password(class="form-control form-control-lg")}}
                <span>{{error}}</span>
                {%endfor%}
                {%else%}
                {{form.password(class="form-control form-control-lg")}}
                {% endif %}
            </div>
            <div class="form-group">
                {{form.confirm_password.label(class="form-control-label")}}
                {% if form.confirm_password.error %}
                {{form.confirm_password(class="form-control form-control-lg is-invalid")}}
                {%for error in form.confirm_password.errors%}
                {{form.confirm_password(class="form-control form-control-lg")}}
                <span>{{error}}</span>
                {%endfor%}
                {%else%}
                {{form.confirm_password(class="form-control form-control-lg")}}
                {% endif %}
            </div>
        </fieldset>
        <div class="field group mt-4">
            {{form.submit(class='btn btn-success')}}
        </div>
    </form>
</div>

{%endblock%}